"""add data freshness tracking columns

Revision ID: 436214dafa80
Revises: 
Create Date: 2025-11-01 07:19:01.409691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436214dafa80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lob_verifications', sa.Column('data_collected_at', sa.DateTime(), nullable=True))
    op.add_column('lob_verifications', sa.Column('data_freshness_score', sa.String(length=50), nullable=True))
    op.add_column('lob_verifications', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lob_verifications', 'last_verified_at')
    op.drop_column('lob_verifications', 'data_freshness_score')
    op.drop_column('lob_verifications', 'data_collected_at')
    # ### end Alembic commands ###
